minio:
  endpoint: localhost:9000
  access_key: minio
  secret_key: minio123
  bucket_name: movie-data
  secure: false

postgresql:
  host: localhost
  port: 5432
  database: movie_analytics
  user: postgres
  password: postgres

crawling:
  start_date: "2024-06-10"
  end_date: "2024-07-01"
